GLOBAL_LIST_INIT(ringlist, list(RING_DISABLED_NAME, RING_CASUAL_NAME, RING_ENGAGEMENT_NAME, RING_WEDDING_NAME, RING_AUSTRALIUM_NAME))

GLOBAL_VAR_INIT(total_beacons, 0)
GLOBAL_VAR_INIT(max_beacons, 100)
