/obj/machinery/mineral/equipment_vendor/Initialize()
	..()
	for(var/datum/data/mining_equipment/R in prize_list)
		if ((R.name == "Minebot Upgrade: A.I.") || (R.name == "Mining Bot Companion"))
			prize_list.Cut(R)
